"""
Q&A service — orchestrates retrieval, history, and LLM response generation.

Flow
----
  1. Ensure the conversation exists (creates one server-side if needed).
  2. Semantic recall: search past conversations for relevant context.
  3. Recency window: get the last N turns of the current conversation.
  4. Document retrieval: pgvector search for relevant chunks.
  5. Prompt assembly: build the LLM input dict from retrieved data.
  6. LLM call: generate the answer.
  7. Persist: embed and write this turn to conversation history.

conversation_id handling
------------------------
If no conversation_id is provided (first message after page load),
ensure_conversation() generates one server-side and returns it.
The caller receives it back in the response and must pass it on
subsequent turns. IDs are never generated by the client.
"""
from __future__ import annotations

import logging
from typing import List, Optional, Tuple

from langchain_core.documents import Document

from src.db.repositories.history_repo import add_turn, ensure_conversation
from src.ingestion.embedder import get_embeddings
from src.llm.llm_factory import get_llm
from src.llm.prompt_builder import build_prompt_inputs
from src.llm.prompts import QA_PROMPT
from src.retrieval.document_retriever import retrieve_chunks
from src.retrieval.history_retriever import (
    retrieve_recent_turns,
    retrieve_relevant_history,
)

logger = logging.getLogger(__name__)


def answer_question(
    question: str,
    history: Optional[List[dict]] = None,
    doc_name: Optional[str] = None,
    session_id: str = "default",
    user_id: Optional[str] = None,
    conversation_id: Optional[str] = None,
) -> dict:
    """
    Answer a question using RAG + conversation history.

    Args:
        question:        The user's question.
        history:         Recent turns passed from the UI (may be empty on refresh).
        doc_name:        Optionally scope retrieval to a single document.
        session_id:      Fallback user identifier when user_id is not provided.
        user_id:         Authenticated user identifier.
        conversation_id: Current conversation ID. If None, a new one is created.

    Returns:
        Dict with keys: answer, sources, retrieved_chunks, conversation_id.
        conversation_id is always present — callers must persist it and pass
        it back on the next turn.
    """
    effective_user_id = user_id or session_id

    # ── 1. Ensure conversation exists ─────────────────────────────────────
    conversation_id = ensure_conversation(
        user_id=effective_user_id,
        conversation_id=conversation_id,
    )

    # ── 2. Semantic recall from past conversations ─────────────────────────
    semantic_history = retrieve_relevant_history(
        query=question,
        user_id=effective_user_id,
        exclude_conversation_id=conversation_id if history else None,
    )

    # ── 3. Recent turns window ─────────────────────────────────────────────
    # Prefer DB-sourced turns (survive page refresh) over the UI-passed list
    # which is lost when the browser reloads.
    recent_turns = history if history else retrieve_recent_turns(
        user_id=effective_user_id,
        conversation_id=conversation_id,
    )

    # ── 4. Document retrieval ──────────────────────────────────────────────
    retrieved: List[Tuple[Document, float]] = retrieve_chunks(
        query=question,
        user_id=effective_user_id,
        doc_name=doc_name,
    )

    # ── 5. Prompt assembly ─────────────────────────────────────────────────
    prompt_inputs = build_prompt_inputs(
        question=question,
        chunks=retrieved,
        recent_turns=recent_turns,
        semantic_history=semantic_history,
    )

    # ── 6. LLM call ────────────────────────────────────────────────────────
    chain = QA_PROMPT | get_llm()
    response = chain.invoke(prompt_inputs)
    answer = response.content if hasattr(response, "content") else str(response)

    # ── 7. Source citations ────────────────────────────────────────────────
    sources = [
        {
            "source":  doc.metadata.get("source", "?"),
            "page":    doc.metadata.get("page", "?"),
            "score":   round(score, 4),
            "snippet": doc.page_content[:250],
            "doc_id":  doc.metadata.get("doc_id", "?"),
        }
        for doc, score in retrieved
    ]

    # ── 8. Persist this turn ───────────────────────────────────────────────
    try:
        vecs = get_embeddings().embed_documents([question, answer[:1000]])
        user_vec, asst_vec = vecs[0], vecs[1]
    except Exception as exc:
        logger.warning(
            "Embedding failed for history turn — storing without vector: %s", exc
        )
        user_vec, asst_vec = None, None

    add_turn(
        user_id=effective_user_id,
        conversation_id=conversation_id,
        user_message=question,
        assistant_message=answer,
        user_vec=user_vec,
        assistant_vec=asst_vec,
    )

    logger.debug(
        "Q: '%.60s' | chunks=%d | user=%s | conv=%s",
        question, len(retrieved), effective_user_id, conversation_id,
    )

    return {
        "answer":           answer,
        "sources":          sources,
        "retrieved_chunks": retrieved,
        "conversation_id":  conversation_id,
    }
